"""Add updated_at to ExchangeRequest

Revision ID: 2e54973693f2
Revises: c16582766289
Create Date: 2024-09-28 16:15:28.069613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e54973693f2'
down_revision = 'c16582766289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_requests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
