"""Change genre field and add is_available field to Book model

Revision ID: 326fb9d8adf7
Revises: 2e54973693f2
Create Date: 2024-09-28 16:48:14.420956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326fb9d8adf7'
down_revision = '2e54973693f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.create_foreign_key('fk_books_genre', 'genres', ['genre_id'], ['id'])
        batch_op.drop_column('genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_books_genre', type_='foreignkey')
        batch_op.drop_column('is_available')
        batch_op.drop_column('genre_id')
    # ### end Alembic commands ###
