"""Update User model to remove password column

Revision ID: 680650970670
Revises: 2daf3289d245
Create Date: 2024-09-28 10:35:33.603455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680650970670'
down_revision = '2daf3289d245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
