"""Add exchange_books association table

Revision ID: 7e79c32c574a
Revises: 680650970670
Create Date: 2024-09-28 11:23:25.607327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e79c32c574a'
down_revision = '680650970670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_books',
    sa.Column('exchange_request_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['exchange_request_id'], ['exchange_requests.id'], ),
    sa.PrimaryKeyConstraint('exchange_request_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_books')
    # ### end Alembic commands ###
